server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8a803.p.ssafy.io:3001/mpti?serverTimezone=Asia/Seoul
    username: ekdrms
    password: ehdrms

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#url: jdbc:mysql://i8a803.p.ssafy.io:3001/mpti?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/mpti?serverTimezone=Asia/Seoul


app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  business:
    url: https://i8a803.p.ssafy.io/api/business/reservation/trainer/reserved/list
  cors:
    ###########테스트를 위해 설정 port : 8081 #############
    allowedOrigins: http://localhost:3000,http://localhost:8002

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      access-key: AKIAVZLMAQJIMJXA7ZEA
      secret-key: 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
    s3: #버킷이름
      bucket: i8a803.p.ssafy.io.baguni
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

